# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('red', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('black', models.IntegerField()),
                ('yellow', models.IntegerField()),
                ('num', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
