# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbreaks', models.PositiveIntegerField(default=0)),
                ('epidemicCount', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='continent',
            name='id',
        ),
        migrations.AlterField(
            model_name='continent',
            name='num',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
