# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latest_version', models.IntegerField()),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(verbose_name='date initiated')),
                ('last_update', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fs_access', models.BooleanField(default=False)),
            ],
        ),
    ]
