# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='page',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
