# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
